#!/bin/bash

#get dir where install script is located
basedir=$(dirname "$(readlink -f "$0")")

################################
#dconf configuration of Cinnamon
#Keybindings
#places of interest
dconf_keybindings=/org/cinnamon/desktop/keybindings/
dconf_hotcorners=/org/cinnamon/hotcorner-layout/

#dconf load /org/cinnamon/desktop/keybindings/ < "${basedir}/resources/dconf keybindings dump"
